# Generated by Django 3.2.5 on 2021-07-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payouts',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
