# Generated by Django 3.2.5 on 2021-07-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_refunds_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_order_id', models.CharField(max_length=50, unique=True)),
                ('r_pay_id', models.CharField(max_length=100, unique=True)),
                ('hook_signature', models.CharField(blank=True, max_length=150, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.order')),
            ],
        ),
    ]
