# Generated by Django 3.2.5 on 2021-07-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Refunds',
        ),
    ]
